# Generated by Django 5.2 on 2026-01-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_workoutlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "part",
                    models.CharField(
                        choices=[
                            ("chest", "胸"),
                            ("back", "背中"),
                            ("legs", "脚"),
                            ("shoulders", "肩"),
                            ("arms", "腕"),
                            ("abs", "腹筋"),
                        ],
                        max_length=20,
                        verbose_name="部位",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="種目名")),
                ("weight", models.FloatField(verbose_name="重量(kg)")),
                ("reps", models.IntegerField(verbose_name="回数")),
                (
                    "one_rm",
                    models.FloatField(blank=True, null=True, verbose_name="推定1RM"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.DeleteModel(
            name="WorkoutLog",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
